### PR TITLE
allow to set a custom host

### LINKED ISSUE #222: Option to run dashboard on localhost only
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [✔] You're running version >=2.1.4 of Parse Server.

- [✔] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Ubuntu 15.10
parse-dashboard v1.0.7 installed with `npm install -g parse-dashboard`

#### Steps to reproduce
`parse-dashboard --config myconfig.json`

#### Logs/Trace
```
The dashboard is now available at http://localhost:4040/
```
```
$ sudo netstat -plaunt | grep 4040
tcp6       0      0 :::4040                 :::*                    LISTEN      32108/node
```
------------------------

Hello,

Is it possible to have the dashboard listen on localhost only?
So far, the app listens on `::` (or IPv4 `0.0.0.0`) by default, which makes the message `available at http://localhost:4040/` confusing.

A possibility would be to have an `--host` option, and/or a `HOST` env var (similarly to the option for the port) and pass it directly to express's `listen()` function along with the port.

My goal is to run the dashboard behind a HTTPS nginx proxy, and by listening on localhost only I can better restrict the access.

### PR DESCRIPTION
**Pull request by hpello**
Fixes  #222

### CODE REVIEW

**Comment by flovilmart** [comment]
I think host is misleading for the beginners as this refers to the bound IP address.

Also, no need to update the address in the README. Locallhost will still be working fine. Not sure 0.0.0.0 will as this represents nothing much for the local machine

**Comment by hpello** [comment]
Thanks for your answer.

Sure. Any suggestion? What about `--address` and `ADDRESS` then?

I see. I had changed the address in the README (as well as in the console.log message) in order not to confuse users, who could think their dashboard is not accessible from the outside (`localhost`) when it actually is (`0.0.0.0`).
But I'll leave `localhost` if you prefer.

**Comment by flovilmart** [comment]
It's just that when people will see: Dashboard running on 'http://0.0.0.0/dashboard' they will paste that on their web browser and won't be able to access it

**Comment by hpello** [comment]
Well, with the current version 1.0.7, it works well for me on Firefox and Chrome :
screen shot 2016-04-05 at 15 48 21

**Comment by flovilmart** [comment]
ok then

**Comment by hpello** [comment]
:+1: 

And for the `adress`/`host` flag and env var?
I liked the `host` one, as it will work with any host, such as `localhost`, `192.168.1.16` or `mywebsite.com`, but I'm fine with what you guys would like.

**Comment by flovilmart** [comment]
we can stick with host, @peterdotjs what do you think?

**Comment by drew-gross** [comment]
I also prefer `localhost` but I'm just going to merge this and then update the docs.

**Pull request merged**
