### PR TITLE
Version 1.0.16

### PR DESCRIPTION
**Pull request by drew-gross**

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
By analyzing the blame information on this pull request, we identified @flovilmart, @durunvo and @dvanwinkle to be potential reviewers.

**Comment by facebook-github-bot-0** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by flovilmart** [comment]
Bad @drew-gross, you should sign those CLA's :)

**Comment by drew-gross** [comment]
Bahahah. Silly facebook github bot.

**Pull request merged**
