### PR TITLE
Change secure check in production environment & Run with Heroku 

### PR DESCRIPTION
**Pull request by gimdongwoo**
req.secure is undefined in production evironment.

It works on heroku with https.

Thank you.

### CODE REVIEW

**Comment by drew-gross** [comment]
Sweet! This looks like it should be pretty close to what we want. The X-Forwarded-Proto header can be spoofed on non-Heroku environments, though, so we need to deal with that. I think the idiomatic `express`-ey solution is to use `app.enable('trust proxy')` and then check `req.proto`. We should only use `trust proxy` if the user says it's OK, though, so that should be toggled with a flag. I think this flag could actually replace the `allowInsecureHTTP` flag, which would be pretty nice security improvement :)

**Comment by mnoble** [comment]
Heh, I was just about open a pull request for this. This will also need to use `req.headers['x-forwarded-for']` when available, in place of `req.connection.remoteAddress`. All requests appear as coming from localhost.

**Comment by gimdongwoo** [comment]
Then I've merged v1.0.5, heroku build fails.

It's logs from heroku.


       > node-sass@3.4.2 postinstall /tmp/build_a465252b863b0e8ad56146460c5c3afb/gimdongwoo-parse-dashboard-b4433e8/node_modules/node-sass
       > node scripts/build.js
       
       ` /tmp/build_a465252b863b0e8ad56146460c5c3afb/gimdongwoo-parse-dashboard-b4433e8/node_modules/node-sass/vendor/linux-x64-47/binding.node ` exists.
       testing binary.
       Binary is fine; exiting.
       npm verb lifecycle node-sass@3.4.2~postinstall: unsafe-perm in lifecycle true
       npm verb lifecycle node-sass@3.4.2~postinstall: PATH: /tmp/build_a465252b863b0e8ad56146460c5c3afb/gimdongwoo-parse-dashboard-b4433e8/.heroku/node/lib/node_modules/npm/bin/node-gyp-bin:/tmp/build_a465252b863b0e8ad56146460c5c3afb/gimdongwoo-parse-dashboard-b4433e8/node_modules/node-sass/node_modules/.bin:/tmp/build_a465252b863b0e8ad56146460c5c3afb/gimdongwoo-parse-dashboard-b4433e8/node_modules/.bin:/tmp/build_a465252b863b0e8ad56146460c5c3afb/gimdongwoo-parse-dashboard-b4433e8/.heroku/node/bin:/tmp/build_a465252b863b0e8ad56146460c5c3afb/gimdongwoo-parse-dashboard-b4433e8/.heroku/node/bin:/app/bin:/app/vendor/bundle/bin:/app/vendor/bundle/ruby/2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/tmp/codon/vendor/bin
       npm verb lifecycle node-sass@3.4.2~postinstall: CWD: /tmp/build_a465252b863b0e8ad56146460c5c3afb/gimdongwoo-parse-dashboard-b4433e8/node_modules/node-sass
       npm info lifecycle defs@1.1.1~postinstall: defs@1.1.1
       npm info lifecycle regenerator@0.8.40~postinstall: regenerator@0.8.40
       npm info lifecycle babel-core@5.8.38~postinstall: babel-core@5.8.38
       npm info lifecycle babel-plugin-remove-proptypes@1.0.3~postinstall: babel-plugin-remove-proptypes@1.0.3
       npm info lifecycle babel-loader@5.3.3~postinstall: babel-loader@5.3.3
       npm info lifecycle basic-auth@1.0.3~postinstall: basic-auth@1.0.3
       npm info lifecycle express@4.13.4~postinstall: express@4.13.4
       npm info lifecycle json-file-plus@3.3.0~postinstall: json-file-plus@3.3.0
       npm info lifecycle package-json@2.3.1~postinstall: package-json@2.3.1
       npm verb unlock done using /app/.npm/_locks/staging-fff6510cd9f8731f.lock for /tmp/build_a465252b863b0e8ad56146460c5c3afb/gimdongwoo-parse-dashboard-b4433e8/node_modules/.staging
       npm info lifecycle parse-dashboard@1.0.5~preinstall: parse-dashboard@1.0.5
       npm info linkStuff parse-dashboard@1.0.5
       npm verb linkBins parse-dashboard@1.0.5
       npm verb linkMans parse-dashboard@1.0.5
       npm info lifecycle parse-dashboard@1.0.5~install: parse-dashboard@1.0.5
       npm info lifecycle parse-dashboard@1.0.5~postinstall: parse-dashboard@1.0.5
       npm info lifecycle parse-dashboard@1.0.5~prepublish: parse-dashboard@1.0.5
       
       > parse-dashboard@1.0.5 prepublish /tmp/build_a465252b863b0e8ad56146460c5c3afb/gimdongwoo-parse-dashboard-b4433e8
       > webpack --config webpack/publish.config.js --progress
       
 59% 53/64 build modulesContainer#eachAtRule is deprecated. Use Container#walkAtRules instead.
       Container#eachRule is deprecated. Use Container#walkRules instead.
       Container#eachDecl is deprecated. Use Container#walkDecls instead.
       Node#removeSelf is deprecated. Use Node#remove.
 31% 82/231 build modulesNode#before is deprecated. Use Node#raws.before
 65% 992/1068 build mo
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

**Comment by drew-gross** [comment]
Heroku seems to be taking issue with the `>=` from 
```js
  "engines": {
    "node": ">=4.3"
  },
```
in `package.json`. Try changing that to use an exact version of `node` and see if that helps. If not, the steps in that troubleshooting link might help (especially the "clean slate" step).

**Comment by gimdongwoo** [comment]
This causes an error during the build on Heroku.
```
[src/dashboard/index.js]
import "babel-polyfill";

```
If it do not use, operation with no problem.

Many people like to use the dashboard on Heroku. So do I.

Thank you!!

**Comment by drew-gross** [comment]
The `babel-polyfill` is important to make sure the dashboard works on older browsers, we can't remove that.

**Pull request closed without merging**
