### PR TITLE
Note that env vars only work with parse-dashboard

### PR DESCRIPTION
**Pull request by Zertz**

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @JeremyPlease, @andrewcbancroft and @drew-gross to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by JeremyPlease** [comment]
Yep, env vars will only work with the `parse-dashboard` command.

**Comment by Zertz** [comment]
Sorry, I wasn't clear, this updates the readme to say so :-)

**Pull request merged**
