### PR TITLE
Add 'Run with Heroku' & Add vars (process.env.*)

### PR DESCRIPTION
**Pull request by gimdongwoo**
Pull Requests for 'Run with Heroku'.
1. Modify (Parse-Dashboard/index.js) related using process.env.*
(PARSE_DASHBOARD_ALLOW_INSECURE_HTTP, APP_ID, SERVER_URL, MASTER_KEY, APP_NAME, CONFIG)
2. Update README.md

Run well on Heroku, but need (NPM_CONFIG_PRODUCTION=false) for using devDependencies.

Thank you!! :+1:

### CODE REVIEW

**Comment by drew-gross** [comment]
Hey, I just made some big changes to how the dashboard is installed, and there are a lot of merge conflicts. Sorry for changing everything out from under you, I'd be happy to merge this if you update it to be on top of the latest index.js.

**Comment by gimdongwoo** [comment]
I wait for updates.
Thanks!

**Comment by gimdongwoo** [comment]
Resolved conflict.
Thank you!

**Comment by gimdongwoo** [comment]
Resolved conflict.
Thank you!

**Comment by drew-gross** [comment]
Hey, I just have a couple of requests:

1) program.X || process.env.X gets repeated sometimes. For each X, could you store it in a variable close to the top of the program for reference

2) `CONFIG` env variable seems likely to collide with other env vars if people are running other apps. Nor a problem on Heroku, but much more likely to be a problem for people running the dashboard locally. Could rename that to `PARSE_DASHBOARD_CONFIG` please?

3) We are trying really hard to avoid recommending the allow insecure HTTP option due to the obvious security concerns around master keys. Can you add some info into the README about why it's safe in this case, and how to ensure it stays safe?

**Comment by gimdongwoo** [comment]
Thank you for your kind code review.
I've fixed all of your recommend.

The use of heroku config vars(process.env.*), referenced in the following.
https://github.com/ParsePlatform/parse-server-example

Have a nice day!

**Comment by drew-gross** [comment]
The code looks good, so I merged this, but following the instructions in the documentation you added doesn't seem to work, as pushing to Heroku doesn't include the built files, so I've removed that documentation. Could you double check the steps you listed and make sure you include steps that work for deploying to Heroku?

**Pull request merged**
