### PR TITLE
fixed calling for error code if theres none

### PR DESCRIPTION
**Pull request by deada92**
#359

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @flovilmart, @drew-gross and @felipemobile to be potential reviewers.

**Comment by facebook-github-bot-1** [comment]
@deada92 updated the pull request.

**Comment by facebook-github-bot-4** [comment]
@deada92 updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@deada92 updated the pull request.

**Comment by deada92** [comment]
sorry for the commits.. I had to remove the conflicts...

**Pull request closed without merging**
