### PR TITLE
#561: Fixes issue with installation conditions that are pointers

### PR DESCRIPTION
**Pull request by dvanwinkle**
Fixes issue #561

### CODE REVIEW

**Comment by steven-supersolid** [comment]
lgtm. Not sure if we want to save the changelog update until the actual release? Could get confusing @flovilmart ?

**Comment by flovilmart** [comment]
There are multiple schools there, Updating the changelog as the PR goes is nice too, so the PR releaser doesn't have to do it :) Many OSS projects do it that way, this document the summary of the changes which is nice. I'd be all in to go in that direction for the dashboard. (and obviously put in in the CONTRIBUTING guide).

**Comment by dvanwinkle** [comment]
I'll happily put it in the CONTRIBUTING guide. I'm a big fan of making this as easy as possible for you all so that we can move faster on releases. I'm also more than happy to help with Release management if you need more people.

**Comment by flovilmart** [comment]
now that travis does the releases for us, it's just a matter of tagging :)

**Comment by flovilmart** [comment]
But yeah @dvanwinkle I would definitely love any additional involvement :)

**Comment by dvanwinkle** [comment]
Updated CONTRIBUTING in #574

**Comment by dvanwinkle** [comment]
@flovilmart Anytime, just let me know what you need.

**Comment by gateway** [comment]
@dvanwinkle thanks for this contribution, been waiting for it for a while, simple small little line of code :)

**Comment by mario** [comment]
Folks, can we get a release with this fix anytime soon? Because this is hitting people a lot :P

**Pull request merged**
