### PR TITLE
Change from basic auth to form based login

### LINKED ISSUE #493: Proposal: Form Based Authentication
The current basic auth implementation works well, but there are a few minor downsides:
- Not all browsers can save basic auth credentials.
- Login persistence can't be controlled (ie. stay logged in for 2 weeks).
- Basic auth username/password is passed as base64 encoded string (technically ok over https).
- Cancelling from browser basic auth just shows "You don't have any apps."

---
### Proposal:
1. Create a page similar to https://www.parse.com/login (stripped down to only have username/password inputs--[screenshot](https://cldup.com/uq9go3Wrm0.PNG)).
2. Redirect to to login page if not authenticated.
3. Verify session on `/parse-dashboard-config.json` route.
4. Continue to use `users` configuration.
5. Use [passport](https://github.com/jaredhanson/passport) and [passport-local](https://github.com/jaredhanson/passport-local) for authentication.
6. Update config loading to set passport configuration options.

---

Any suggestions, concerns, or objections?

### PR DESCRIPTION
**Pull request by JeremyPlease**
### Summary
- Created page at `/login`
- Uses [passport](https://github.com/jaredhanson/passport) and [passport-local](https://github.com/jaredhanson/passport-local) for authentication.
- Stores session in cookie to work across servers and server restarts.
- No configuration changes needed. Still uses `users`.
- Redirects unauthenticated requests to `/login`

This resolves #493

### CODE REVIEW

**Comment by dvanwinkle** [comment]
@JeremyPlease It doesn't look like you added any tests. It'd be really nice to see some, and also make sure that you didn't break any existing tests.

**Comment by flovilmart** [comment]
Do we really need passport/passport-local? I'm kinda opinionated with dependency usage :) and you can just tell me it would take a very long time to implement without it :)

**Comment by deada92** [comment]
I can review it if the tests that will be added pass..

**Comment by steven-supersolid** [comment]
Suggest we remove the editor config and lint rules/setup until a decision has been made on these.

**Comment by JeremyPlease** [comment]
_(sorry it looks like my email reply didn't get posted here)_

Thank you everyone for all the feedback! I'll try to respond in detail and provide a meaningful update within the next 24 hours or so.

**Comment by flovilmart** [comment]
No problemo!

**Comment by JeremyPlease** [comment]
Thank you everyone for all the feedback! I'll try to respond in detail and
provide a meaningful update within the next 24 hours or so.

**Comment by JeremyPlease** [comment]
Thank you everyone for all the feedback! I'll try to respond in detail and
provide a meaningful update within the next 24 hours or so.
 





On Mon, Oct 24, 2016 10:51 PM, Florent Vilmart notifications@github.com
wrote:
@flovilmart  requested changes on this pull request.

Thanks @JeremyPlease  for that one! Most wanted feature it seems. Can you
address the few comments here and there and we'll be able to move forward with
that!


--------------------------------------------------------------------------------

In src/components/LoginForm/LoginForm.react.js:

> +import CSRFInput from 'components/CSRFInput/CSRFInput.react';
+import Icon               from 'components/Icon/Icon.react';
+import PropTypes          from 'lib/PropTypes';
+import React              from 'react';
+import styles             from 'components/LoginForm/LoginForm.scss';
+import { verticalCenter } from 'stylesheets/base.scss';
+
+// Class-style component, because we need refs
+export default class LoginForm extends React.Component {
+  render() {
+    return (
+      <div className={styles.login} style={{ marginTop: this.props.marginTop || '-220px' }}>
+        <Icon width={80} height={80} name='infinity' fill='#093A59' />
+        <form method='post' ref='form' action={this.props.endpoint} className={styles.form}>
+          {
+            //<CSRFInput />


Can we have CSRF taken care of?


--------------------------------------------------------------------------------

In src/login/index.js:

> + * Copyright (c) 2016-present, Parse, LLC
+ * All rights reserved.
+ *
+ * This source code is licensed under the license found in the LICENSE file in
+ * the root directory of this source tree.
+ */
+import Login    from './Login';
+import React    from 'react';
+import ReactDOM from 'react-dom';
+
+require('stylesheets/fonts.scss');
+
+// App entry point
+
+var path = window.PARSE_DASHBOARD_PATH || '/';
+ReactDOM.render(<Login path={path}/>, document.getElementById('login_mount'));


We want the trailing \n ;)

**Comment by flovilmart** [comment]
@JeremyPlease seems that your email came in :)

**Comment by JeremyPlease** [comment]
Alrighty. Finally some time to make some updates!

@dvanwinkle Current tests pass and I added a couple more. The overall repo definitely needs more tests though.

@steven-supersolid I'll move eslint/editorconfig to a new PR.

@flovilmart:
• We could implement without `passport`, but it would take a bit of time that I don't think I'll have soon. Besides `passport` and `passport-local` have proven stable in my other work, are pretty light, and have nearly no external  dependencies :)
• I added CSRF (pretty much the same way parse.com has it implemented).
• I cleaned up some code.

---------

Please let me know if anyone has any other feedback, concerns, or requests.

Thanks again!

**Comment by flovilmart** [comment]
I'll conduct some local testing, as that is a security feature :)

**Comment by dvanwinkle** [comment]
At least from a code perspective, 👍

**Comment by JeremyPlease** [comment]
Anyone interested in testing locally, here are the steps:

1. `git clone -b form-login git@github.com:JeremyPlease/parse-dashboard.git`
2. `cd parse-dashboard`
3. `npm install`
4. Edit file at `./Parse-Dashboard/parse-dashboard-config.json` to have `"users"` defined and apps pointed to a real Parse server ([example config](https://f.jerm.me/d0VI4G/parse-dashboard-config.json)).
5. `npm run dev`
6. Open browser to [http://localhost:4040](http://localhost:4040)

**Comment by JeremyPlease** [comment]
_bump_

Anyone have any questions or concerns? 

@flovilmart anything you'd like to see changed?

**Comment by mario** [comment]
Would love to see this merged if you're all ok with it.

**Comment by flovilmart** [comment]
Sorry it's taking forever...

**Comment by deada92** [comment]
any eta for the merge @flovilmart ?

**Comment by flovilmart** [comment]
All changes look good, I'm a bit scared of merging but that should be fine :)

**Comment by steven-supersolid** [comment]
Looks like there are a couple of existing tests for authentication and these still pass, plus a few tests added. So as long as we trust those tests then I think it should be OK too.

**Comment by steven-supersolid** [comment]
One small optional change - since the review was created we're encouraging contributors to update the changelog with their changes to reduce overhead.

**Comment by flovilmart** [comment]
I'll take care of adding it to the changelog for the next release ;)

**Comment by gowridev** [comment]
I hope, this logic works well with [parse server example](https://github.com/ParsePlatform/parse-server-examplel) . Can we extend this logic to apply authorization on parse classes?

**Comment by vkeepe** [comment]
Getting this error:

`Error: Illegal arguments: undefined, string
   at Error (native)
   at Object.bcrypt.compareSync (/usr/lib/node_modules/parse-dashboard/node_modules/bcryptjs/dist/bcrypt.js:230:19)
   at userToTest.validUsers.validUsers.find.user (/usr/lib/node_modules/parse-dashboard/Parse-Dashboard/Authentication.js:91:65)
   at Array.find (native)
   at Authentication.authenticate (/usr/lib/node_modules/parse-dashboard/Parse-Dashboard/Authentication.js:88:21)
   at /usr/lib/node_modules/parse-dashboard/Parse-Dashboard/Authentication.js:40:21
   at pass (/usr/lib/node_modules/parse-dashboard/node_modules/passport/lib/authenticator.js:347:9)
   at Authenticator.deserializeUser (/usr/lib/node_modules/parse-dashboard/node_modules/passport/lib/authenticator.js:352:5)
   at SessionStrategy.authenticate (/usr/lib/node_modules/parse-dashboard/node_modules/passport/lib/strategies/session.js:53:28)
   at attempt (/usr/lib/node_modules/parse-dashboard/node_modules/passport/lib/middleware/authenticate.js:348:16)`

**Comment by JeremyPlease** [comment]
@vkeepe Check out issue #609

**Pull request merged**
