### PR TITLE
Enabling web hooks

### PR DESCRIPTION
**Pull request by davimacedo**

### CODE REVIEW

**Comment by drew-gross** [comment]
Please delete the Heroku code completely rather than just commenting it out.

**Comment by davimacedo** [comment]
Just done

**Comment by davimacedo** [comment]
@drew-gross can you please check it again?

**Comment by apersaud** [comment]
Hi everyone, any updates allowing this on the dashboard. Would be very useful to have it integrated before the shutdown date.

**Comment by mrmarcsmith** [comment]
+1

**Comment by henninghorn** [comment]
+1

**Comment by shurco** [comment]
+1

**Comment by mmarshak** [comment]
Hey all, is there a tutorial or guide how to use the web hook.

I checked the guide in the url - http://parseplatform.org/docs/cloudcode/guide/ and I do not see any reference to it.

**Pull request merged**
