### PR TITLE
Adds support for viewing parse-server based jobs

### PR DESCRIPTION
**Pull request by flovilmart**
- Removes the scheduled endpoint (we don't schedule on parse-server)
- Adds /all endpoint with just run method
- Supports _JobStatus query

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
By analyzing the blame information on this pull request, we identified @drew-gross, @JeremyPlease and @Marco129 to be potential reviewers.

**Comment by JeremyPlease** [comment]
Nice! Looks great to me.

**Comment by drew-gross** [comment]
Looks good to me too. My only suggestion would be to add a line to the list of available features in `package.json`.

**Comment by facebook-github-bot-9** [comment]
@flovilmart updated the pull request - [view changes](https://github.com/ParsePlatform/parse-dashboard/pull/514/files/bf5afbc484b8fd6e61749c6f0bc9fe76355ab12d..4951e5076b9c2c98b8bdb76568e41d8ffd5ab823)

**Comment by flovilmart** [comment]
@drew-gross let me know if the line is good :)

**Comment by dvanwinkle** [comment]
@drew-gross @flovilmart Looks good to me.

**Pull request merged**
