### PR TITLE
Version 1.0.18

### PR DESCRIPTION
**Pull request by drew-gross**

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @Beingbook, @flovilmart and @durunvo to be potential reviewers.

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by Beingbook** [comment]
It looks my previous PR makes a problem. Sorry, I will consider deeply next time.

**Comment by drew-gross** [comment]
It's fine, happens to all of us. Hopefully we can add test cases to prevent regressions like this in the future.

**Pull request merged**
