### PR TITLE
Add link to how to run on Heroku

### PR DESCRIPTION
**Pull request by mattgoldspink**
Also added a new section to the Readme so that other platform setups can be contributed either as Wiki pages or blog posts

### CODE REVIEW

**Comment by natanrolnik** [comment]
@mattgoldspink do you think you could squash the commits in one single commit?

**Comment by noder199** [comment]
Is there a way to stop somebody from just visiting the link and messing with your database?

**Comment by drew-gross** [comment]
Since your guide uses the --allowInsecureHTTP option, can you include in your guide how to ensure that Heroku does not allow HTTP? Using HTTPS only is incredibly important for the dashboard.

**Comment by mattgoldspink** [comment]
@natanrolnik Sure - let me get that fixed.

@drew-gross So I added that flag because when on Heroku the proxy forwards requests over http and hence you end up with.

image

I'll file a seperate ticket for this, but we should perhaps either add another flag which enables http if the "X-Forwarded-Proto" is https, or extend the existing flag to allow http requests if the "X-Forwarded-Proto" header is set.

@noder199 Can you explain a little bit more about what you mean? The example I gave sets up the user/pass in the config ensuring users have to log in. Are you talking about something else?

**Comment by flovilmart** [comment]
X-Forwarded-Proto is not safe, any HTTP client could set it and force the server to serve on HTTP thinking it's safe...

**Comment by mattgoldspink** [comment]
@flovilmart Agreed - let me open a separate ticket to discuss this on.

**Comment by drew-gross** [comment]
Using the --allowInsecureHTTP flag is find if you have SSL termination somewhere earlier in your request handling, and that layer refuses non HTTPS. If you can explain in your guide why it's safe to use in this case, I'd be happy to merge :)

**Comment by gateway** [comment]
I added my way to get the dashboard running with Heroku .. its up and running fine.  #250

**Comment by mattgoldspink** [comment]
@drew-gross Added an "Important Note" section to the article explaining that in general --allowInsecureHTTP flag shouldn't be set, but in this case it is valid. Also included a link to the open ticket about improving for proxies. Let me know if it needs tweaking.

**Comment by cherukumilli** [comment]
# parse-dashboard-example
If anyone is interested then please check out and give me feedback about my **parse-dashboard-example** project. It is similar to the **parse-server-example**.

Please check it out at: `https://github.com/cherukumilli/parse-dashboard-example`

**Comment by drew-gross** [comment]
Closing due to lack of activity

**Pull request closed without merging**
