### PR TITLE
Add an 'Add a Class' entry to the edit menu

### PR DESCRIPTION
**Pull request by bgw**
The data browser 'Edit' menu has related options like 'Add a Row' or 'Delete this class', so 'Add a class' is a natural addition.

### CODE REVIEW

**Comment by peterdotjs** [comment]
nice! one nit - could we add it at the bottom of the menu with a separator?
        
```
<Separator />
<MenuItem text='Add a class' onClick={onAddClass} />
```

My reasoning is that other actions are specific to the class itself. And this is for creating a new class.

**Comment by drew-gross** [comment]
I actually like it where it is - all the "add" operations are grouped and all the "delete" operations are grouped.

**Comment by adampietrasiak** [comment]
There is a lot of space there, My skills don't allow me to make PR, but from my UX experience I see it like it's begging to make some icons there instead of dropdown to reduce task from 2 clicks to 1 click and to make you instantly see what you can do.

**Comment by drew-gross** [comment]
@adampietrasiak agreed - I would love to see it responsively move items from the toolbar to the dropdown as the browser window shrinks. That is a bigger effort though :) A medium amount of effort would be to have all the items always in the dropdown, and have only the toolbar be responsive.

**Comment by peterdotjs** [comment]
@drew-gross it is nice that they are grouped together but odd that it is isn't specific to this class like the others. I don't think it's really worth arguing about. I'll go ahead and merge.

@adampietrasiak we had some plans to move the actions out of the dropdown towards the left side of the header which would make for better accessibility but we never got to it.

**Comment by bgw** [comment]
I'd be interested in taking a stab at implementing some sort of responsive toolbar, if people think it's worth the engineering effort.

**Pull request merged**
